In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv("AJAKANGAHM.csv")

sample_col = "Sample"

In [37]:
metals = ["Fe","Pb", "Cu","Cr", "Mn", "Zn", "Ni", "Co", "Cd"]

In [38]:
# ============================================================
# CHILDREN EXPOSURE PARAMETERS
# Based on USEPA Exposure Factors Handbook
# ============================================================

# ------------------------------------------------------------
# Exposure parameters
# ------------------------------------------------------------

IR = 1.0          # ingestion rate (L/day)
EF = 365          # exposure frequency (days/year)
ED = 6            # exposure duration (years)
BW = 15           # body weight (kg)

AT_nc = ED * 365  # averaging time non-cancer
AT_c = 70 * 365   # averaging time cancer


# ------------------------------------------------------------
# Dermal exposure parameters
# ------------------------------------------------------------

SA = 6600         # exposed skin area (cm2)
Kp = 0.001        # dermal permeability coefficient (cm/hr)
ET = 1.0          # exposure time (hr/day)
CF = 0.001        # unit conversion factor
ABS = 0.001       # dermal absorption factor


# ------------------------------------------------------------
# Inhalation exposure parameters
# ------------------------------------------------------------

InhR = 7.6        # inhalation rate (m3/day)
PEF = 1.36e9      # particle emission factor


# ============================================================
# ORAL CANCER SLOPE FACTORS (CSF)
# Units: (mg/kg-day)^-1
# ============================================================

INGEST_SF = {
    'Fe': 0,
    'Pb': 0.0085,
    'Cu': 0,
    'Cr': 0.5,
    'Mn': 0,
    'Zn': 0,
    'Ni': 0.84,
    'Co': 0,
    'Cd': 0.38
}


# ============================================================
# DERMAL CANCER SLOPE FACTORS
# ============================================================

DERMAL_CSF = {
    'Fe': 0,
    'Pb': 0.017,
    'Cu': 0,
    'Cr': 20.0,
    'Mn': 0,
    'Zn': 0,
    'Ni': 22.75,
    'Co': 0,
    'Cd': 7.6
}


# ============================================================
# INHALATION CANCER SLOPE FACTORS
# ============================================================

INHALATION_CSF = {
    'Fe': 0,
    'Pb': 0.042,
    'Cu': 0,
    'Cr': 42.0,
    'Mn': 0,
    'Zn': 0,
    'Ni': 0.84,
    'Co': 9.8,
    'Cd': 6.3
}


# ============================================================
# INHALATION UNIT RISK
# ============================================================

INHALATION_IUR = {
    'Fe': 0,
    'Pb': 0.000012,
    'Cu': 0,
    'Cr': 0.012,
    'Mn': 0,
    'Zn': 0,
    'Ni': 0.00026,
    'Co': 0.009,
    'Cd': 0.0018
}


# ============================================================
# ORAL REFERENCE DOSE (RfD)
# Units: mg/kg-day
# ============================================================

ORAL_RfD = {
    'Fe': 0.7,
    'Pb': 0.0035,
    'Cu': 0.04,
    'Cr': 0.003,
    'Mn': 0.14,
    'Zn': 0.3,
    'Ni': 0.02,
    'Co': 0.02,
    'Cd': 0.001
}


# ============================================================
# DERMAL REFERENCE DOSE
# ============================================================

DERMAL_RfD = {
    'Fe': 0.14,
    'Pb': 0.000525,
    'Cu': 0.008,
    'Cr': 0.00006,
    'Mn': 0.00185,
    'Zn': 0.06,
    'Ni': 0.0008,
    'Co': 0.016,
    'Cd': 0.00001
}


# ============================================================
# INHALATION REFERENCE DOSE
# ============================================================

INHALATION_RfD = {
    'Fe': 0.00022,
    'Pb': 0.0035,
    'Cu': 0.04,
    'Cr': 0.0002,
    'Mn': 0.0000143,
    'Zn': 0.3,
    'Ni': 0.002,
    'Co': 0.00003,
    'Cd': 0.001
}

In [39]:
def calculate_cdi_ingestion_child(df):

    results = []

    for metal in metals:

        if metal in df.columns:

            CDI = (df[metal] * IR * EF * ED) / (BW * AT_nc)

            for i,val in enumerate(CDI):

                results.append([
                    df[sample_col].iloc[i],
                    metal,
                    val
                ])

    table_ingestion = pd.DataFrame(results,
        columns=["Sample","Metal","CDI_Ingestion_Child"])

    table_ingestion.to_csv("Ajakanga_output\\Child_risk\\CDI_Ingestion_Child.csv",index=False)

    return table_ingestion

In [48]:
calculate_cdi_dermal_child(df)
calculate_cdi_inhalation_child(df)
calculate_cdi_ingestion_child(df)

    Sample Metal  CDI_Ingestion_Child
0     AJA1    Fe             0.248800
1     AJA2    Fe             0.173067
2     AJA3    Fe             0.138533
3     AJA4    Fe             0.016067
4     AJA5    Fe             0.065800
..     ...   ...                  ...
220  AJA21    Cd             0.001867
221  AJA22    Cd             0.002333
222  AJA23    Cd             0.001467
223  AJA24    Cd             0.000733
224  AJA25    Cd             0.000533

[225 rows x 3 columns]

In [41]:
def calculate_cdi_dermal_child(df):

    results = []

    for metal in metals:

        if metal in df.columns:

            CDI = (
                df[metal] * SA * Kp * ET * EF * ED * CF
            ) / (BW * AT_nc)

            for i,val in enumerate(CDI):

                results.append([
                    df[sample_col].iloc[i],
                    metal,
                    val
                ])

    table_dermal = pd.DataFrame(results,
        columns=["Sample","Metal","CDI_Dermal_Child"])

    table_dermal.to_csv("Ajakanga_output\\Child_risk\\CDI_Dermal_Child.csv",index=False)

    return table_dermal

In [42]:
def calculate_cdi_inhalation_child(df):

    results = []

    for metal in metals:

        if metal in df.columns:

            CDI = (
                df[metal] * InhR * EF * ED
            ) / (PEF * BW * AT_nc)

            for i,val in enumerate(CDI):

                results.append([
                    df[sample_col].iloc[i],
                    metal,
                    val
                ])

    table_inhale = pd.DataFrame(results,
        columns=["Sample","Metal","CDI_Inhalation_Child"])

    table_inhale.to_csv("Ajakanga_output\\Child_risk\\CDI_Inhalation_Child.csv",index=False)

    return table_inhale

In [43]:
def calculate_hq_ingestion(cdi_table, RfD):

    results = []

    for i,row in cdi_table.iterrows():

        metal = row["Metal"]

        if metal in RfD:

            HQ = row["CDI_Ingestion_Child"] / RfD[metal]

            results.append([
                row["Sample"],
                metal,
                row["CDI_Ingestion_Child"],
                HQ
            ])

    table = pd.DataFrame(results,
        columns=["Sample","Metal","CDI","HQ"])

    table.to_csv("Ajakanga_output\\Child_risk\\HQ_Ingestion_Child.csv",index=False)

    return table

In [49]:
CDI_DERMAL = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Dermal_Child.csv")
CDI_INGEST = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Ingestion_Child.csv")
CDI_INHALE = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Inhalation_Child.csv")

In [50]:
calculate_hq_dermal(CDI_DERMAL, DERMAL_RfD)
calculate_hq_ingestion(CDI_INGEST, ORAL_RfD)
calculate_hq_inhalation(CDI_INHALE, INHALATION_RfD)

    Sample Metal           CDI            HQ
0     AJA1    Fe  1.390353e-09  6.319786e-06
1     AJA2    Fe  9.671373e-10  4.396078e-06
2     AJA3    Fe  7.741569e-10  3.518895e-06
3     AJA4    Fe  8.978431e-11  4.081105e-07
4     AJA5    Fe  3.677059e-10  1.671390e-06
..     ...   ...           ...           ...
220  AJA21    Cd  1.043137e-11  1.043137e-08
221  AJA22    Cd  1.303922e-11  1.303922e-08
222  AJA23    Cd  8.196078e-12  8.196078e-09
223  AJA24    Cd  4.098039e-12  4.098039e-09
224  AJA25    Cd  2.980392e-12  2.980392e-09

[225 rows x 4 columns]

In [45]:
def calculate_hq_dermal(cdi_table, RfD):

    results = []

    for i,row in cdi_table.iterrows():

        metal = row["Metal"]

        if metal in RfD:

            HQ = row["CDI_Dermal_Child"] / RfD[metal]

            results.append([
                row["Sample"],
                metal,
                row["CDI_Dermal_Child"],
                HQ
            ])

    table = pd.DataFrame(results,
        columns=["Sample","Metal","CDI","HQ"])

    table.to_csv("Ajakanga_output\\Child_risk\\HQ_Dermal_Child.csv",index=False)

    return table

In [51]:
cdi_ingestion_table = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Ingestion_Child.csv")
cdi_dermal_table = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Dermal_Child.csv")
cdi_inhalation_table = pd.read_csv("Ajakanga_output\\Child_risk\\CDI_Inhalation_Child.csv")

In [52]:
def calculate_hq_inhalation(cdi_table, RfD):

    results = []

    for i,row in cdi_table.iterrows():

        metal = row["Metal"]

        if metal in RfD:

            HQ = row["CDI_Inhalation_Child"] / RfD[metal]

            results.append([
                row["Sample"],
                metal,
                row["CDI_Inhalation_Child"],
                HQ
            ])

    table = pd.DataFrame(results,
        columns=["Sample","Metal","CDI","HQ"])

    table.to_csv("Ajakanga_output\\Child_risk\\HQ_Inhalation_Child.csv",index=False)

    return table

In [53]:
def calculate_cr_ingest_child(cdi_ingestion_table, CSF):

    results = []

    for i,row in cdi_ingestion_table.iterrows():

        metal = row["Metal"]

        if metal in CSF:

            CR = row["CDI_Ingestion_Child"] * CSF[metal]

            results.append([
                row["Sample"],
                metal,
                row["CDI_Ingestion_Child"],
                CR
            ])

    table = pd.DataFrame(results,
        columns=["Sample","Metal","CDI","Cancer_Risk"])

    table.to_csv("Ajakanga_output\\Child_risk\\CR_Ingestion_Child.csv",index=False)

    return table

In [54]:
def calculate_cr_dermal_child(cdi_dermal_table, CSF):

    results = []

    for i,row in cdi_dermal_table.iterrows():

        metal = row["Metal"]

        if metal in CSF:

            CR = row["CDI_Dermal_Child"] * CSF[metal]

            if CR < 1e-6:
                classification = "Negligible"
                interpretation = "Insignificant cancer risk"

            elif CR <= 1e-4:
                classification = "Acceptable"
                interpretation = "Within acceptable cancer risk range"

            else:
                classification = "High Risk"
                interpretation = "Potential carcinogenic risk"

            results.append([
                row["Sample"],
                metal,
                row["CDI_Dermal_Child"],
                CSF[metal],
                CR,
                classification,
                interpretation
            ])

    cr_dermal_table = pd.DataFrame(
        results,
        columns=[
            "Sample",
            "Metal",
            "CDI_Dermal",
            "CSF",
            "Cancer_Risk_Dermal",
            "CR_Class",
            "CR_Interpretation"
        ]
    )

    cr_dermal_table.to_csv("Ajakanga_output\\Child_risk\\CR_Dermal_Child.csv", index=False)

    return cr_dermal_table

In [55]:
def calculate_cr_inhalation_child(cdi_inhalation_table, CSF):

    results = []

    for i,row in cdi_inhalation_table.iterrows():

        metal = row["Metal"]

        if metal in CSF:

            CR = row["CDI_Inhalation_Child"] * CSF[metal]

            if CR < 1e-6:
                classification = "Negligible"
                interpretation = "Insignificant cancer risk"

            elif CR <= 1e-4:
                classification = "Acceptable"
                interpretation = "Within acceptable cancer risk range"

            else:
                classification = "High Risk"
                interpretation = "Potential carcinogenic risk"

            results.append([
                row["Sample"],
                metal,
                row["CDI_Inhalation_Child"],
                CSF[metal],
                CR,
                classification,
                interpretation
            ])

    cr_inhalation_table = pd.DataFrame(
        results,
        columns=[
            "Sample",
            "Metal",
            "CDI_Inhalation",
            "CSF",
            "Cancer_Risk_Inhalation",
            "CR_Class",
            "CR_Interpretation"
        ]
    )

    cr_inhalation_table.to_csv("Ajakanga_output\\Child_risk\\CR_Inhalation_Child.csv", index=False)

    return cr_inhalation_table

In [58]:
calculate_cr_inhalation_child(CDI_INHALE, INHALATION_CSF)
calculate_cr_dermal_child(CDI_DERMAL, DERMAL_CSF)
calculate_cr_ingest_child(CDI_INGEST, INGEST_SF)

    Sample Metal       CDI  Cancer_Risk
0     AJA1    Fe  0.248800     0.000000
1     AJA2    Fe  0.173067     0.000000
2     AJA3    Fe  0.138533     0.000000
3     AJA4    Fe  0.016067     0.000000
4     AJA5    Fe  0.065800     0.000000
..     ...   ...       ...          ...
220  AJA21    Cd  0.001867     0.000709
221  AJA22    Cd  0.002333     0.000887
222  AJA23    Cd  0.001467     0.000557
223  AJA24    Cd  0.000733     0.000279
224  AJA25    Cd  0.000533     0.000203

[225 rows x 4 columns]

In [60]:
import pandas as pd

# ====================================
# IMPORT DATA
# ====================================

hq_ing = pd.read_csv("Ajakanga_output\\Child_risk\\HQ_Ingestion_Child.csv")
hq_der = pd.read_csv("Ajakanga_output\\Child_risk\\HQ_Dermal_Child.csv")
hq_inh = pd.read_csv("Ajakanga_output\\Child_risk\\HQ_Inhalation_Child.csv")

cr_ing = pd.read_csv("Ajakanga_output\\Child_risk\\CR_Ingestion_Child.csv")
cr_der = pd.read_csv("Ajakanga_output\\Child_risk\\CR_Dermal_Child.csv")
cr_inh = pd.read_csv("Ajakanga_output\\Child_risk\\CR_Inhalation_Child.csv")

# ====================================
# HAZARD INDEX (HI) PER PATHWAY
# ====================================

def calculate_hi(df, pathway):

    hi = (
        df.groupby("Sample")["HQ"]
        .sum()
        .reset_index()
    )

    hi.rename(columns={"HQ": "HI"}, inplace=True)
    hi["Pathway"] = pathway

    hi.to_csv(f"Ajakanga_output\\Child_risk\\HI_{pathway}.csv", index=False)

    return hi


hi_ing = calculate_hi(hq_ing, "Ingestion")
hi_der = calculate_hi(hq_der, "Dermal")
hi_inh = calculate_hi(hq_inh, "Inhalation")

# ====================================
# TOTAL HAZARD INDEX (HI_total)
# ====================================

all_hi = pd.concat([hi_ing, hi_der, hi_inh])

hi_total = (
    all_hi.groupby("Sample")["HI"]
    .sum()
    .reset_index()
)

hi_total.rename(columns={"HI": "HI_Total"}, inplace=True)

hi_total.to_csv("Ajakanga_output\\Child_risk\\HI_Total.csv", index=False)

# ====================================
# TOTAL CANCER RISK PER PATHWAY
# ====================================

def calculate_tcr_pathway(df, pathway):

    tcr = (
        df.groupby("Sample")["Cancer_Risk"]
        .sum()
        .reset_index()
    )

    tcr.rename(columns={"Cancer_Risk": "TCR"}, inplace=True)
    tcr["Pathway"] = pathway

    tcr.to_csv(f"Ajakanga_output\\Child_risk\\TCR_{pathway}.csv", index=False)

    return tcr


tcr_ing = calculate_tcr_pathway(cr_ing, "Ingestion")
tcr_der = calculate_tcr_pathway(cr_der, "Dermal")
tcr_inh = calculate_tcr_pathway(cr_inh, "Inhalation")

# ====================================
# TOTAL CANCER RISK (ALL PATHWAYS)
# ====================================

all_tcr = pd.concat([tcr_ing, tcr_der, tcr_inh])

tcr_total = (
    all_tcr.groupby("Sample")["TCR"]
    .sum()
    .reset_index()
)

tcr_total.rename(columns={"TCR": "Total_Cancer_Risk"}, inplace=True)

tcr_total.to_csv("Ajakanga_output\\Child_risk\\TCR_Total.csv", index=False)

# ====================================
# OPTIONAL: MERGED RISK SUMMARY TABLE
# ====================================

summary = hi_total.merge(tcr_total, on="Sample")

summary.to_csv("Ajakanga_output\\Child_risk\\Risk_Assessment_Summary.csv", index=False)

print("All risk metrics successfully calculated and exported.")

All risk metrics successfully calculated and exported.