In [17]:
import pandas as pd
import numpy as np

def load_data():

    data = pd.read_csv("Aja_cat_an.csv")

    return data

In [18]:
data = load_data()

In [19]:
def calculate_sar(data):

    sar = data["Na"] / np.sqrt((data["Ca"] + data["Mg"]) / 2)

    classification = []
    interpretation = []

    for val in sar:

        if val < 10:
            classification.append("Excellent")
            interpretation.append("Suitable for irrigation with minimal sodium hazard")

        elif val < 18:
            classification.append("Good")
            interpretation.append("Suitable for most soils with moderate management")

        elif val < 26:
            classification.append("Doubtful")
            interpretation.append("May cause soil permeability problems")

        else:
            classification.append("Unsuitable")
            interpretation.append("Severe sodium hazard")

    result = pd.DataFrame({
        "Sample": data.Sample,
        "SAR": sar.round(3),
        "Class": classification,
        "Interpretation": interpretation
    })

    result.to_csv("Ajakanga_output/SAR_results.csv", index=False)

    return result

In [20]:
calculate_sar(data)

   Sample    SAR      Class                                     Interpretation
0    AJA1  4.568  Excellent  Suitable for irrigation with minimal sodium ha...
1    AJA2  4.613  Excellent  Suitable for irrigation with minimal sodium ha...
2    AJA3  4.429  Excellent  Suitable for irrigation with minimal sodium ha...
3    AJA4  2.183  Excellent  Suitable for irrigation with minimal sodium ha...
4    AJA5  2.663  Excellent  Suitable for irrigation with minimal sodium ha...
5    AJA6  2.695  Excellent  Suitable for irrigation with minimal sodium ha...
6    AJA7  2.086  Excellent  Suitable for irrigation with minimal sodium ha...
7    AJA8  3.126  Excellent  Suitable for irrigation with minimal sodium ha...
8    AJA9  2.151  Excellent  Suitable for irrigation with minimal sodium ha...
9   AJA10  2.709  Excellent  Suitable for irrigation with minimal sodium ha...
10  AJA11  1.960  Excellent  Suitable for irrigation with minimal sodium ha...
11  AJA12  3.042  Excellent  Suitable for irrigation with minimal sodium ha...
12  AJA13  1.828  Excellent  Suitable for irrigation with minimal sodium ha...
13  AJA14  3.103  Excellent  Suitable for irrigation with minimal sodium ha...
14  AJA15  2.629  Excellent  Suitable for irrigation with minimal sodium ha...
15  AJA16  2.863  Excellent  Suitable for irrigation with minimal sodium ha...
16  AJA17  2.887  Excellent  Suitable for irrigation with minimal sodium ha...
17  AJA18  1.800  Excellent  Suitable for irrigation with minimal sodium ha...
18  AJA19  3.007  Excellent  Suitable for irrigation with minimal sodium ha...
19  AJA20  2.852  Excellent  Suitable for irrigation with minimal sodium ha...
20  AJA21  4.477  Excellent  Suitable for irrigation with minimal sodium ha...
21  AJA22  4.274  Excellent  Suitable for irrigation with minimal sodium ha...
22  AJA23  4.330  Excellent  Suitable for irrigation with minimal sodium ha...
23  AJA24  4.459  Excellent  Suitable for irrigation with minimal sodium ha...
24  AJA25  4.370  Excellent  Suitable for irrigation with minimal sodium ha...

In [21]:
def calculate_na_percent(data):

    na_percent = ((data["Na"] + data["K"]) /
                 (data["Ca"] + data["Mg"] + data["Na"] + data["K"])) * 100

    classes=[]
    interp=[]

    for val in na_percent:

        if val < 20:
            classes.append("Excellent")
            interp.append("Safe irrigation water")

        elif val < 40:
            classes.append("Good")
            interp.append("Suitable for irrigation")

        elif val < 60:
            classes.append("Permissible")
            interp.append("Acceptable with moderate soil management")

        elif val < 80:
            classes.append("Doubtful")
            interp.append("Potential sodium hazard")

        else:
            classes.append("Unsuitable")
            interp.append("Not recommended for irrigation")

    result = pd.DataFrame({
        "Sample": data.Sample,
        "Na%": na_percent.round(2),
        "Class": classes,
        "Interpretation": interp
    })

    result.to_csv("Ajakanga_output/NaPercent_results.csv", index=False)

    return result

In [22]:
calculate_na_percent(data)

   Sample    Na% Class           Interpretation
0    AJA1  28.65  Good  Suitable for irrigation
1    AJA2  29.72  Good  Suitable for irrigation
2    AJA3  29.44  Good  Suitable for irrigation
3    AJA4  22.22  Good  Suitable for irrigation
4    AJA5  25.74  Good  Suitable for irrigation
5    AJA6  25.83  Good  Suitable for irrigation
6    AJA7  23.14  Good  Suitable for irrigation
7    AJA8  28.06  Good  Suitable for irrigation
8    AJA9  23.61  Good  Suitable for irrigation
9   AJA10  26.02  Good  Suitable for irrigation
10  AJA11  23.44  Good  Suitable for irrigation
11  AJA12  26.69  Good  Suitable for irrigation
12  AJA13  21.87  Good  Suitable for irrigation
13  AJA14  25.49  Good  Suitable for irrigation
14  AJA15  26.88  Good  Suitable for irrigation
15  AJA16  28.59  Good  Suitable for irrigation
16  AJA17  27.99  Good  Suitable for irrigation
17  AJA18  20.54  Good  Suitable for irrigation
18  AJA19  29.09  Good  Suitable for irrigation
19  AJA20  27.72  Good  Suitable for irrigation
20  AJA21  31.09  Good  Suitable for irrigation
21  AJA22  30.43  Good  Suitable for irrigation
22  AJA23  30.21  Good  Suitable for irrigation
23  AJA24  30.59  Good  Suitable for irrigation
24  AJA25  30.09  Good  Suitable for irrigation

In [23]:
def calculate_kr(data):

    kr = data["Na"] / (data["Ca"] + data["Mg"])

    classification=[]
    interp=[]

    for val in kr:

        if val < 1:
            classification.append("Suitable")
            interp.append("Water suitable for irrigation")

        else:
            classification.append("Unsuitable")
            interp.append("Excess sodium may affect soil permeability")

    result = pd.DataFrame({
        "Sample": data.Sample,
        "KR": kr.round(3),
        "Class": classification,
        "Interpretation": interp
    })

    result.to_csv("Ajakanga_output/KR_results.csv", index=False)

    return result

In [24]:
calculate_kr(data)

   Sample     KR     Class                 Interpretation
0    AJA1  0.286  Suitable  Water suitable for irrigation
1    AJA2  0.314  Suitable  Water suitable for irrigation
2    AJA3  0.311  Suitable  Water suitable for irrigation
3    AJA4  0.192  Suitable  Water suitable for irrigation
4    AJA5  0.211  Suitable  Water suitable for irrigation
5    AJA6  0.213  Suitable  Water suitable for irrigation
6    AJA7  0.183  Suitable  Water suitable for irrigation
7    AJA8  0.251  Suitable  Water suitable for irrigation
8    AJA9  0.192  Suitable  Water suitable for irrigation
9   AJA10  0.214  Suitable  Water suitable for irrigation
10  AJA11  0.171  Suitable  Water suitable for irrigation
11  AJA12  0.233  Suitable  Water suitable for irrigation
12  AJA13  0.161  Suitable  Water suitable for irrigation
13  AJA14  0.223  Suitable  Water suitable for irrigation
14  AJA15  0.221  Suitable  Water suitable for irrigation
15  AJA16  0.244  Suitable  Water suitable for irrigation
16  AJA17  0.238  Suitable  Water suitable for irrigation
17  AJA18  0.160  Suitable  Water suitable for irrigation
18  AJA19  0.257  Suitable  Water suitable for irrigation
19  AJA20  0.234  Suitable  Water suitable for irrigation
20  AJA21  0.329  Suitable  Water suitable for irrigation
21  AJA22  0.312  Suitable  Water suitable for irrigation
22  AJA23  0.312  Suitable  Water suitable for irrigation
23  AJA24  0.322  Suitable  Water suitable for irrigation
24  AJA25  0.311  Suitable  Water suitable for irrigation

In [25]:
#residual sodium carbonate
def calculate_rsc(data):

    rsc = (data["CO3"] + data["HCO3"]) - (data["Ca"] + data["Mg"])

    classes=[]
    interp=[]

    for val in rsc:

        if val < 1.25:
            classes.append("Safe")
            interp.append("Suitable for irrigation")

        elif val < 2.5:
            classes.append("Marginal")
            interp.append("May require soil management")

        else:
            classes.append("Unsuitable")
            interp.append("High alkalinity hazard")

    result = pd.DataFrame({
        "Sample": data.Sample,
        "RSC": rsc.round(3),
        "Class": classes,
        "Interpretation": interp
    })

    result.to_csv("Ajakanga_output/RSC_results.csv", index=False)

    return result

In [26]:
calculate_rsc(data)

   Sample     RSC       Class          Interpretation
0    AJA1  224.16  Unsuitable  High alkalinity hazard
1    AJA2  204.38  Unsuitable  High alkalinity hazard
2    AJA3  202.40  Unsuitable  High alkalinity hazard
3    AJA4  125.38  Unsuitable  High alkalinity hazard
4    AJA5  140.24  Unsuitable  High alkalinity hazard
5    AJA6  144.15  Unsuitable  High alkalinity hazard
6    AJA7  125.22  Unsuitable  High alkalinity hazard
7    AJA8  144.58  Unsuitable  High alkalinity hazard
8    AJA9  125.05  Unsuitable  High alkalinity hazard
9   AJA10  147.74  Unsuitable  High alkalinity hazard
10  AJA11  124.56  Unsuitable  High alkalinity hazard
11  AJA12  156.68  Unsuitable  High alkalinity hazard
12  AJA13  125.78  Unsuitable  High alkalinity hazard
13  AJA14  178.91  Unsuitable  High alkalinity hazard
14  AJA15  131.11  Unsuitable  High alkalinity hazard
15  AJA16  132.96  Unsuitable  High alkalinity hazard
16  AJA17  134.43  Unsuitable  High alkalinity hazard
17  AJA18  124.66  Unsuitable  High alkalinity hazard
18  AJA19  131.39  Unsuitable  High alkalinity hazard
19  AJA20  129.82  Unsuitable  High alkalinity hazard
20  AJA21  204.50  Unsuitable  High alkalinity hazard
21  AJA22  194.89  Unsuitable  High alkalinity hazard
22  AJA23  217.74  Unsuitable  High alkalinity hazard
23  AJA24  209.25  Unsuitable  High alkalinity hazard
24  AJA25  219.53  Unsuitable  High alkalinity hazard

In [27]:
def calculate_mh(data):

    mh = (data["Mg"] / (data["Ca"] + data["Mg"])) * 100

    classes=[]
    interp=[]

    for val in mh:

        if val < 50:
            classes.append("Suitable")
            interp.append("Magnesium hazard is low")

        else:
            classes.append("Unsuitable")
            interp.append("High magnesium hazard affecting soil quality")

    result = pd.DataFrame({
        "Sample": data.Sample,
        "MH": mh.round(2),
        "Class": classes,
        "Interpretation": interp
    })

    result.to_csv("Ajakanga_output/MH_results.csv", index=False)

    return result

In [28]:
calculate_mh(data)

   Sample     MH     Class           Interpretation
0    AJA1  26.56  Suitable  Magnesium hazard is low
1    AJA2  29.54  Suitable  Magnesium hazard is low
2    AJA3  29.51  Suitable  Magnesium hazard is low
3    AJA4  25.39  Suitable  Magnesium hazard is low
4    AJA5  24.80  Suitable  Magnesium hazard is low
5    AJA6  24.43  Suitable  Magnesium hazard is low
6    AJA7  26.27  Suitable  Magnesium hazard is low
7    AJA8  27.76  Suitable  Magnesium hazard is low
8    AJA9  26.97  Suitable  Magnesium hazard is low
9   AJA10  27.47  Suitable  Magnesium hazard is low
10  AJA11  26.27  Suitable  Magnesium hazard is low
11  AJA12  29.34  Suitable  Magnesium hazard is low
12  AJA13  25.83  Suitable  Magnesium hazard is low
13  AJA14  28.45  Suitable  Magnesium hazard is low
14  AJA15  26.25  Suitable  Magnesium hazard is low
15  AJA16  26.68  Suitable  Magnesium hazard is low
16  AJA17  26.34  Suitable  Magnesium hazard is low
17  AJA18  26.22  Suitable  Magnesium hazard is low
18  AJA19  26.70  Suitable  Magnesium hazard is low
19  AJA20  28.39  Suitable  Magnesium hazard is low
20  AJA21  26.12  Suitable  Magnesium hazard is low
21  AJA22  26.07  Suitable  Magnesium hazard is low
22  AJA23  26.71  Suitable  Magnesium hazard is low
23  AJA24  26.19  Suitable  Magnesium hazard is low
24  AJA25  25.61  Suitable  Magnesium hazard is low

In [29]:
weights = {
"Ca":2,
"Mg":2,
"Na":3,
"K":1,
"HCO3":2,
"CO3":2,
"Cl":3,
"SO4":3
}

standards = {
"Ca":75,
"Mg":50,
"Na":200,
"K":12,
"HCO3":300,
"CO3":75,
"Cl":250,
"SO4":250
}

In [30]:
def calculate_wqi(data):

    parameters=list(weights.keys())

    qi=[]
    wi=[]

    for p in parameters:

        qi.append((data[p] / standards[p]) * 100)
        wi.append(weights[p])

    qi_df=pd.concat(qi,axis=1)
    qi_df.columns=parameters

    wqi=(qi_df * wi).sum(axis=1) / sum(wi)

    classes=[]
    interp=[]

    for val in wqi:

        if val < 50:
            classes.append("Excellent")
            interp.append("Water suitable for drinking and irrigation")

        elif val < 100:
            classes.append("Good")
            interp.append("Minor quality concerns")

        elif val < 200:
            classes.append("Poor")
            interp.append("Treatment recommended")

        elif val < 300:
            classes.append("Very Poor")
            interp.append("Limited suitability")

        else:
            classes.append("Unsuitable")
            interp.append("Not safe for consumption")

    result=pd.DataFrame({
        "Sample":data.Sample,
        "WQI":wqi.round(2),
        "Class":classes,
        "Interpretation":interp
    })

    result.to_csv("Ajakanga_output/WQI_results.csv",index=False)

    return result

In [31]:
calculate_wqi(data)

   Sample    WQI      Class                              Interpretation
0    AJA1  53.63       Good                      Minor quality concerns
1    AJA2  45.91  Excellent  Water suitable for drinking and irrigation
2    AJA3  43.19  Excellent  Water suitable for drinking and irrigation
3    AJA4  25.13  Excellent  Water suitable for drinking and irrigation
4    AJA5  33.02  Excellent  Water suitable for drinking and irrigation
5    AJA6  33.07  Excellent  Water suitable for drinking and irrigation
6    AJA7  26.02  Excellent  Water suitable for drinking and irrigation
7    AJA8  33.16  Excellent  Water suitable for drinking and irrigation
8    AJA9  25.29  Excellent  Water suitable for drinking and irrigation
9   AJA10  33.63  Excellent  Water suitable for drinking and irrigation
10  AJA11  26.72  Excellent  Water suitable for drinking and irrigation
11  AJA12  35.93  Excellent  Water suitable for drinking and irrigation
12  AJA13  25.44  Excellent  Water suitable for drinking and irrigation
13  AJA14  40.20  Excellent  Water suitable for drinking and irrigation
14  AJA15  29.97  Excellent  Water suitable for drinking and irrigation
15  AJA16  30.04  Excellent  Water suitable for drinking and irrigation
16  AJA17  31.71  Excellent  Water suitable for drinking and irrigation
17  AJA18  24.42  Excellent  Water suitable for drinking and irrigation
18  AJA19  29.83  Excellent  Water suitable for drinking and irrigation
19  AJA20  32.06  Excellent  Water suitable for drinking and irrigation
20  AJA21  41.69  Excellent  Water suitable for drinking and irrigation
21  AJA22  42.32  Excellent  Water suitable for drinking and irrigation
22  AJA23  43.27  Excellent  Water suitable for drinking and irrigation
23  AJA24  43.41  Excellent  Water suitable for drinking and irrigation
24  AJA25  44.10  Excellent  Water suitable for drinking and irrigation